version: '3.3'
services:
 saludos:
   image: rrojano/jdk8 
   volumes:
   - ./saludos-0.0.1-SNAPSHOT.jar:/app/saludos-0.0.1-SNAPSHOT.jar
   ports:
   - 8080:8080
   command:
   - java
   - -jar
   - /app/saludos-0.0.1-SNAPSHOT.jar
